window.GT_SETTINGS = {
  BASE_PATH: "growtopia-test",
  LOG_VIEWER_USERNAMES: ["isxt"],
  ADMIN_USERNAMES: ["isxt"],
  TILE_SIZE: 32,
  WORLD_WIDTH_TILES: 140,
  WORLD_HEIGHT_TILES: 30,
  PLAYER_WIDTH: 22,
  PLAYER_HEIGHT: 30,
  GRAVITY: 0.32,
  FRICTION_GROUND: 0.86,
  FRICTION_AIR: 0.94,
  AIR_CONTROL: 0.6,
  MOVE_ACCEL: 0.46,
  MAX_MOVE_SPEED: 3.7,
  JUMP_VELOCITY: -7.2,
  MAX_FALL_SPEED: 10,
  JUMP_COOLDOWN_MS: 200
};
